linters:
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
  disable:
    - depguard
    - forbidigo
    - gofumpt
    - paralleltest
    - varnamelen
    - wsl
    - tagalign
    - exhaustruct
    - nlreturn
    - wrapcheck
