services:
  db:
    image: ghcr.io/5e-bits/5e-database:latest
    # build: ../5e-database
    ports:
      - "27017:27017"

  biscuit-dnd-go:
    environment:
      MONGODB_HOST: db
    build: .
    command: make test
    depends_on:
      - db
